<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="FluentValidation">
            <HintPath>..\..\..\.nuget\packages\fluentvalidation\12.0.0-preview1\lib\net8.0\FluentValidation.dll</HintPath>
        </Reference>
        <Reference Include="MediatR">
            <HintPath>..\..\..\.nuget\packages\mediatr\12.4.1\lib\net6.0\MediatR.dll</HintPath>
        </Reference>
        <Reference Include="MediatR.Contracts">
          <HintPath>..\..\..\.nuget\packages\mediatr.contracts\2.0.1\lib\netstandard2.0\MediatR.Contracts.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="12.4.1" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    </ItemGroup>

</Project>
