<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="FluentValidation">
            <HintPath>..\..\..\.nuget\packages\fluentvalidation\12.0.0-preview1\lib\net8.0\FluentValidation.dll</HintPath>
        </Reference>
        <Reference Include="MediatR">
            <HintPath>..\..\..\.nuget\packages\mediatr\12.4.1\lib\net6.0\MediatR.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CQRS\CQRS.csproj"/>
    </ItemGroup>

</Project>
